print('Exercício 9: programa que lê um número qualquer e mostre a sua tabuada.')
print('\033[34;m' '-=' '\033[m' * 20)
print('\033[1;35;mCalculador de tabuada\033[m')
print('\033[34;m' '-=' '\033[m' * 20)
n = int(input('Para começar, diga um número:'))
print('A tabuada deste número é:')
print('\033[1;34;m' '-' '\033[m' * 12)
print('{} x 1 = {}'.format(n, n * 1))
print('{} x 2 = {}'.format(n, n * 2))
print('{} x 3 = {}'.format(n, n * 3))
print('{} x 4 = {}'.format(n, n * 4))
print('{} x 5 = {}'.format(n, n * 5))
print('{} x 6 = {}'.format(n, n * 6))
print('{} x 7 = {}'.format(n, n * 7))
print('{} x 8 = {}'.format(n, n * 8))
print('{} x 9 = {}'.format(n, n * 9))
print('{} x 10 = {}'.format(n, n * 10))
print('\033[1;34;m' '-' '\033[m' * 12)
